### ISSUE TITLE
Resource names can include varying URLs

### ISSUE THREAD

**Issue by kzlsakal** [thiamsantos/spandex_tesla#9]
The resource name of a span is generated as `<METHOD> <URL>`.

As resource names are often used to categorize resources on APMs, requests
with varying URLs can truly be a pain because they would have different
resource names each time.

We can allow grouping resources with certain patterns such as naming
a request made to `https://website.com/user/1d8f11c8-e2eb-47f2-8f6f-9f58cbdd7c21`
as `https://website.com/user/<user-id>`.

Please see merge request https://github.com/thiamsantos/spandex_tesla/pull/8

**Comment by thiamsantos** [comment]
Closed by #8
